version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: install dependencies
          command: |
            go mod download
      - run:
          name: run tests
          command: |
            go test ./... -race -cover -v 2>&1
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
